apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mlops-data
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: mlflow
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: mlops-data
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
