apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect
  namespace: mlops-app
spec:
  selector:
    matchLabels:
      app: prefect
  replicas: 1
  template:
    metadata:
      labels:
        app: prefect
    spec:
      containers:
        - name: prefect
          image:  mlops-prefect:v1.0.0
          imagePullPolicy: Never
          env:
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: MLFLOW_TRACKING_URI
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: MLFLOW_S3_ENDPOINT_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"

